---
# tasks file for fcc

- name: install packages
  become: yes
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ fcc_packages }}"


- name: install application
  become: yes
  git:
    repo: '{{ fcc_repo_location }}'
    dest: '{{ fcc_application_location }}'


- name: install requirements
  become: yes
  shell: >
    pip install -r {{ fcc_application_location }}/requirements.txt


- name: make it accessible by anyone
  become: yes
  shell: "chmod -R ug=rwX,o=rX {{ fcc_application_location }}"

