before_script:
  - cd /tmp && curl https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip | unzip && cp /tmp/terraform /usr/local/bin/terraform.io
  - cd /tmp && curl https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip | unzip && cp /tmp/packer /usr/local/bin/packer.io
  - pip install ansible --update
jobs:
  include:
    - stage: build
      script: make ami
    - stage: deploy
      script: make live